#! /usr/bin/env python3
import argparse
import sys
import matplotlib.pyplot as plt
import re
from os import path

parser = argparse.ArgumentParser()
parser.add_argument('infile', nargs='?')
parser.add_argument('-o', '--output')
parser.add_argument('-t', '--title')
parser.add_argument('-x', '--xlabel', default='data')
parser.add_argument('-y', '--ylabel', default='frequency')
parser.add_argument('-b', '--buckets', default=50, type=int)
parser.add_argument('--no-grid', default=False, action='store_true')
args = parser.parse_args()

args.no_grid

input = sys.stdin if args.infile is None else args.infile
data = [ float(i) for i in input ]

if args.infile:
    args.title = args.title or '.'.join(args.infile.split('.')[0:-1])
else:
    args.title = args.title or path.basename(sys.argv[0])

args.output = args.output or re.sub(r'[^a-zA-Z0-9 ]', '', args.title).replace(' ', '-') + '.png'
plt.hist(data, args.buckets)
plt.title(args.title)
plt.xlabel(args.xlabel)
plt.ylabel(args.ylabel)
plt.grid(not args.no_grid)
plt.savefig(args.output)
print('generated ' + args.output)
